version: 0.0
os: linux
files:
   - source: /
     destination: /usr/share/nginx/html/wordpress
permissions:
   - object: /usr/share/nginx/html/wordpress
     pattern: "**"
     owner: nginx
     group: nginx
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: .script/installpackages.sh
      runas: root
   AfterInstall:
    - location: .script/restartnginx.sh
      runas: root