version: 0.0
os: linux
files:
   - source: /
     destination: /usr/share/nginx/html/wordpress
hooks:
   BeforeInstall:
    - location: .scripts/installpackages.sh
      runas: root
   AfterInstall:
    - location: .scripts/restartnginx.sh
      runas: root